### ISSUE TITLE
Lots of errors

### ISSUE THREAD

**Issue by ArcAIN6** [wirekraken/ESP8266-Websockets-LED#1]
Seems after 2 years, a lot has changed :D 

Throws an abundance of errors when trying to compile to upload using latest esptool, esp8266 board info for arduino, and fastled 3.x

**Comment by 5ch4um1** [comment]
What are your errors exactly? Probably related to missing libraries? I just compiled and uploaded this with arduino ide 1.8.13 to a wemos d1 mini without any issues, works like a charm? Just makes me want to learn russian so i can understand the comments. spaciba @wirekraken

**Comment by wirekraken** [comment]
Legacy code has been updated
