### ISSUE TITLE
Please, do not tell people to power the LEDs through the microcontroller

### ISSUE THREAD

**Issue by roboter-basteln** [wirekraken/ESP8266-Websockets-LED#10]
> you can be powered directly from ESP, but the diodes will "flicker"

A single pin of a ESP8266 can only provide 12 mA. The ESP8266 can provide only 1000 mA in total.
A single pin of a ESP32 can only provide 40 mA. The ESP32 can only provide 1200 mA in total.
A single pin of an Arduiono can only provide 20 mA constantly. An Arduino can provide ~400 mA on USB and 900 mA with a power supply.

Given these numbers, let's choose the highest, 1200 mA. With an RGB LED fully lit, that's 60 mA per LED, so you can only power 20 of them. With any LED strip of a decent length, like 3 meters of 60 LEDs per meter, the current can easily exceed 10 Amps (not mA).

**Comment by wirekraken** [comment]
You're right. For development, I used a strip with 60 leds, with such a number nodemcu copes well. With a large number of course it is dangerous. I forgot to mention it. Thanks for the remark.
