### ISSUE TITLE
LED_COUNT

### ISSUE THREAD

**Issue by Vasek-R** [wirekraken/ESP8266-Websockets-LED#2]
Thanks for your code it saved me a lot of time 👍 
Hi using your project I found that if the number of leds exceed 254 program does not start.
Using the same library FastLED v3.3.3 by Danie Garcia with other sketch works fine with higher number of leds
more i found I have to add
#define FASTLED_ALLOW_INTERRUPTS 0
#define FASTLED_INTERRUPT_RETRY_COUNT 0
#define FASTLED_ESP8266_RAW_PIN_ORDER
//before
#include <FastLED.h>
could you pls check if there is a possible type conflict with LED_COUNT?
Spasibo bolshoe 🥇

**Comment by crazy888** [comment]
If habe the same problem. LED_COUNT > 254 brakes the programm. Feels being a SHORT only.

UPDATE: I found the problem. You need to correct datatype of LED_COUNT in led_effects.ino to make it work.

In the attachment you can find the working ino file.

Running acutally with 448 LEDs. Thanks for the sketch!!!


[led_effects.zip](https://github.com/wirekraken/ESP8266-Websockets-LED/files/5742381/led_effects.zip)

**Comment by rmaksim** [comment]
see **led_effects.ino**
`void updateColor(...){...}`

`for(uint8_t i=0...`

need replace **uint8_t** -> **uint16_t**

**Comment by rmaksim** [comment]
in **led_effect.ino**

`void updateColor(...{...}`

`for(uint8_t i`

need replace **uint8_t** -> **int**
