### ISSUE TITLE
Soft WDT resets

### ISSUE THREAD

**Issue by TeodorBankov** [wirekraken/ESP8266-Websockets-LED#5]
Hello, I am trying to run your code on my ESP8266 and am getting soft WDT resets in the serial monitor. I will provide the code and anything else if necessary.

**Comment by TeodorBankov** [comment]
Okay, seems like the problem is when I add more than 255 LEDs in the code, it begins to WDT soft reset. Is there any easy solution that I can add to the code?

**Comment by rmaksim** [comment]
see solution in #2 (replace uint8_t -> uint16_t)

**Comment by rmaksim** [comment]
see solution in #2 (need replace **uint8_t** -> **int**)
