### ISSUE TITLE
NONISSUE Python script to sync lights with monitor

### ISSUE THREAD

**Issue by TanmayChhatbar** [wirekraken/ESP8266-Websockets-LED#6]
https://github.com/TanMaySee/SyncMyLEDs/blob/main/README.md
I've made this, and didn't know of another way to contact you.
I've been using your repo to power a strip of LEDs behind my monitor, and made this to learn how to use websockets in python.

**Comment by dipan29** [comment]
Great Work Tanmay. But recently I was unable to build out of it. This error was throwing while compiling the Arduino code -

```
fastpin.h:207:24: error: static assertion failed: Invalid pin specified
  207 |  static_assert(validpin(), "Invalid pin specified");
      |                ~~~~~~~~^~
exit status 1
call of overloaded 'abs(uint32_t)' is ambiguous
```

Any ideas?

**Comment by dipan29** [comment]
Can you help @wirekraken ??

**Comment by TanmayChhatbar** [comment]
If you're talking of the script I made, it isn't meant to be flashed on your Arduino.
It's meant to run on your PC. It captures a screenshot of your desktop, and relays a color command to the strip that is controlled by wirekraken's code. I've explained the usage in its README.Hope this helps. Let me know if you have any issues.

**Comment by dipan29** [comment]
No no I didn't mean that. Anyway solved the problem. Thanks
